name: Terraform CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: aws-secure-s3

      - name: Terraform Validate
        run: terraform validate
        working-directory: aws-secure-s3

      - name: Terraform Plan
        run: |
          export TF_VAR_aws_access_key=$AWS_ACCESS_KEY_ID
          export TF_VAR_aws_secret_key=$AWS_SECRET_ACCESS_KEY
          terraform plan
        working-directory: aws-secure-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
           projectBaseDir: aws-secure-s3
           args: >
             -Dsonar.organization=night12pm-sonar-org
             -Dsonar.projectKey=terraform_s3_project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
